apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshelter-stg
  namespace: argocd
spec:
  project: openshelter
  source:
    repoURL: https://github.com/cuedego/openshelter.git
    targetRevision: main
    path: platform/gitops/helm/charts/openshelter-stack
    helm:
      valueFiles:
        - ../../values/stg/openshelter-stack.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openshelter-stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
