{{- if .Values.zabbix.enabled }}
# ExternalSecret for the RDS password used by zabbix-server
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-zabbix-rds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshelter.labels" . | nindent 4 }}
    {{- include "openshelter.zabbix.selectorLabels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.zabbix.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-zabbix-rds
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: {{ .Values.zabbix.secrets.rdsPassword.remoteRef }}
---
# ExternalSecret for the Zabbix admin password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-zabbix-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshelter.labels" . | nindent 4 }}
    {{- include "openshelter.zabbix.selectorLabels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.zabbix.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-zabbix-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: {{ .Values.zabbix.secrets.adminPassword.remoteRef }}
{{- end }}
