{{- if .Values.zabbix.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-zabbix
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshelter.labels" . | nindent 4 }}
    {{- include "openshelter.zabbix.selectorLabels" . | nindent 4 }}
  {{- with .Values.serviceAccount.zabbix.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.mqtt.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-mqtt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshelter.labels" . | nindent 4 }}
    {{- include "openshelter.mqtt.selectorLabels" . | nindent 4 }}
  {{- with .Values.serviceAccount.mqtt.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
