global:
  environment: dev
zabbix:
  enabled: true
  image:
    repository: "052081665529.dkr.ecr.eu-central-1.amazonaws.com/openshelter/zabbix"
    tag: "fa9d4cf"
  db:
    host: "openshelter-dev-rds.cjws62ie8i3t.eu-central-1.rds.amazonaws.com"
  ingress:
    enabled: true
  secrets:
    rdsPassword:
      remoteRef: "openshelter-dev/rds/password"
    adminPassword:
      remoteRef: "openshelter-dev/zabbix/admin-password"
mqtt:
  enabled: true
  image:
    repository: "052081665529.dkr.ecr.eu-central-1.amazonaws.com/openshelter/mqtt"
    tag: "fa9d4cf"
  secrets:
    password:
      remoteRef: "openshelter-dev/mqtt/password"
