global:
  environment: dev

zabbix:
  enabled: true
  image:
    repository: "REPLACE_ME.dkr.ecr.REPLACE_AWS_REGION.amazonaws.com/openshelter/zabbix"
    tag: "0.1.0"
  db:
    host: "REPLACE_ME.rds.amazonaws.com"
  ingress:
    enabled: true
  secrets:
    rdsPassword:
      remoteRef: "openshelter-dev/rds/password"
    adminPassword:
      remoteRef: "openshelter-dev/zabbix/admin-password"

mqtt:
  enabled: true
  image:
    repository: "REPLACE_ME.dkr.ecr.REPLACE_AWS_REGION.amazonaws.com/openshelter/mqtt"
    tag: "0.1.0"
  secrets:
    password:
      remoteRef: "openshelter-dev/mqtt/password"
