global:
  environment: stg
zabbix:
  enabled: true
  image:
    repository: "052081665529.dkr.ecr.eu-central-1.amazonaws.com/openshelter/zabbix"
    tag: "ff61d65"
  db:
    host: "openshelter-stg-rds.cjws62ie8i3t.eu-central-1.rds.amazonaws.com"
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
  secrets:
    rdsPassword:
      remoteRef: "openshelter-stg/rds/password"
    adminPassword:
      remoteRef: "openshelter-stg/zabbix/admin-password"
mqtt:
  enabled: true
  image:
    repository: "052081665529.dkr.ecr.eu-central-1.amazonaws.com/openshelter/mqtt"
    tag: "ff61d65"
  secrets:
    password:
      remoteRef: "openshelter-stg/mqtt/password"
