global:
  environment: stg

serviceAccount:
  zabbix:
    annotations:
      eks.amazonaws.com/role-arn: "REPLACE_ME_ZABBIX_IRSA_ROLE_ARN"
  mqtt:
    annotations:
      eks.amazonaws.com/role-arn: "REPLACE_ME_MQTT_IRSA_ROLE_ARN"

zabbix:
  enabled: true
  image:
    repository: "REPLACE_ME.dkr.ecr.us-east-1.amazonaws.com/openshelter/zabbix"
    tag: "0.1.0"
  db:
    host: "REPLACE_ME.rds.amazonaws.com"
  secrets:
    rdsPassword:
      remoteRef: "openshelter-stg/rds/password"
    adminPassword:
      remoteRef: "openshelter-stg/zabbix/admin-password"

mqtt:
  enabled: true
  image:
    repository: "REPLACE_ME.dkr.ecr.us-east-1.amazonaws.com/openshelter/mqtt"
    tag: "0.1.0"
  secrets:
    password:
      remoteRef: "openshelter-stg/mqtt/password"
