global:
  environment: prod
zabbix:
  enabled: true
  replicaCount: 2
  image:
    repository: "052081665529.dkr.ecr.eu-central-1.amazonaws.com/openshelter/zabbix"
    tag: "f81d861"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  db:
    host: "openshelter-prod-rds.cjws62ie8i3t.eu-central-1.rds.amazonaws.com"
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: "REPLACE_ACM_CERTIFICATE_ARN"
  secrets:
    rdsPassword:
      remoteRef: "openshelter-prod/rds/password"
    adminPassword:
      remoteRef: "openshelter-prod/zabbix/admin-password"
mqtt:
  enabled: true
  replicaCount: 2
  image:
    repository: "052081665529.dkr.ecr.eu-central-1.amazonaws.com/openshelter/mqtt"
    tag: "f81d861"
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  secrets:
    password:
      remoteRef: "openshelter-prod/mqtt/password"
